"""The BeyondNN trace schema (schema version 0.1).

Pure data: immutable records with content-derived ids, explicit epistemic
status, lineage, and strict versioned serialisation. Importing this package does
not import ``torch``.

Stable in 0.1 (ADR-014): the record mechanism and envelope, ``InputRecord``,
``OutputRecord``, ``ActivationRecord``, ``TensorRef``, ``TraceLimitation``, and the
claim types (ADR-012), and the provenance types (M1.2, ADR-019). Later-phase record
kinds arrive in later schema versions.
"""

from ._canonical import JsonMap
from .attribution import (
    AttributionBaseline,
    AttributionMethodSpec,
    AttributionRecord,
    AttributionReduction,
    BaselineKind,
)
from .audit import (
    AlternativeCriteria,
    AuditAxis,
    AuditedClaim,
    AuditedConcept,
    AuditPlan,
    CounterexampleRule,
    EvidenceRequirement,
    Invariance,
    SelectionSubject,
)
from .base import BaseRecord, EvidenceRef, RecordRef, verify_ref
from .claims import (
    Assessment,
    AssessmentPolicy,
    Claim,
    ClaimRef,
    ClaimTestResult,
    ClaimTestSpec,
    PolicyRequirement,
    ResultRef,
    SpecRef,
    derive_verdict,
)
from .codec import SCHEMA_VERSION, from_dict, from_json, to_dict, to_json
from .concepts import (
    AssessmentSummary,
    ConceptActivation,
    ConceptDataset,
    ConceptPolicy,
    ConceptRecord,
    ConceptValidation,
    FeatureBasis,
    FeatureRecord,
    FeatureSource,
    GeneratedLabel,
    LabelSource,
    SAEIdentity,
    derive_semantic_status,
)
from .errors import (
    DecodeError,
    EvidenceRuleError,
    IntegrityError,
    SchemaError,
    SchemaTypeError,
    UnknownLimitationCodeError,
    UnknownRecordKindError,
    UnsupportedVersionError,
)
from .faithfulness import (
    AspectOutcome,
    CheckOutcome,
    EvidenceSelection,
    ProtocolResult,
    SelectionSource,
)
from .interventions import (
    CausalEffect,
    InterventionOperation,
    InterventionRecord,
    MetricDeclaration,
    MetricSpec,
)
from .limitations import LIMITATIONS, LimitationDef, Severity, TraceLimitation
from .provenance import (
    EnvironmentIdentity,
    ExecutionContext,
    ExecutionMode,
    ExecutionOccurrence,
    FingerprintMethod,
    MethodIdentity,
    ModelDeclaration,
    ModelIdentity,
    ProvenanceRecord,
    Randomness,
)
from .records import ActivationRecord, InputRecord, OutputRecord
from .status import (
    ALLOWED_PARENT_STATUSES,
    CAUSAL_EVIDENCE_STATUSES,
    CAUSAL_RELATIONS,
    EstimandScope,
    EvidenceStatus,
    Outcome,
    Relation,
    SemanticStatus,
    Verdict,
)
from .values import (
    ClaimSource,
    ClaimSourceKind,
    Estimand,
    NamedTensor,
    Site,
    SiteIO,
    Subject,
    TargetSpec,
    TensorRef,
    TensorStats,
)

__all__ = [
    "ALLOWED_PARENT_STATUSES",
    "CAUSAL_EVIDENCE_STATUSES",
    "CAUSAL_RELATIONS",
    "LIMITATIONS",
    "SCHEMA_VERSION",
    "ActivationRecord",
    "AlternativeCriteria",
    "AspectOutcome",
    "Assessment",
    "AssessmentPolicy",
    "AssessmentSummary",
    "AttributionBaseline",
    "AttributionMethodSpec",
    "AttributionRecord",
    "AttributionReduction",
    "AuditAxis",
    "AuditPlan",
    "AuditedClaim",
    "AuditedConcept",
    "BaseRecord",
    "BaselineKind",
    "CausalEffect",
    "CheckOutcome",
    "Claim",
    "ClaimRef",
    "ClaimSource",
    "ClaimSourceKind",
    "ClaimTestResult",
    "ClaimTestSpec",
    "ConceptActivation",
    "ConceptDataset",
    "ConceptPolicy",
    "ConceptRecord",
    "ConceptValidation",
    "CounterexampleRule",
    "DecodeError",
    "EnvironmentIdentity",
    "Estimand",
    "EstimandScope",
    "EvidenceRef",
    "EvidenceRequirement",
    "EvidenceRuleError",
    "EvidenceSelection",
    "EvidenceStatus",
    "ExecutionContext",
    "ExecutionMode",
    "ExecutionOccurrence",
    "FeatureBasis",
    "FeatureRecord",
    "FeatureSource",
    "FingerprintMethod",
    "GeneratedLabel",
    "InputRecord",
    "IntegrityError",
    "InterventionOperation",
    "InterventionRecord",
    "Invariance",
    "JsonMap",
    "LabelSource",
    "LimitationDef",
    "MethodIdentity",
    "MetricDeclaration",
    "MetricSpec",
    "ModelDeclaration",
    "ModelIdentity",
    "NamedTensor",
    "Outcome",
    "OutputRecord",
    "PolicyRequirement",
    "ProtocolResult",
    "ProvenanceRecord",
    "Randomness",
    "RecordRef",
    "Relation",
    "ResultRef",
    "SAEIdentity",
    "SchemaError",
    "SchemaTypeError",
    "SelectionSource",
    "SelectionSubject",
    "SemanticStatus",
    "Severity",
    "Site",
    "SiteIO",
    "SpecRef",
    "Subject",
    "TargetSpec",
    "TensorRef",
    "TensorStats",
    "TraceLimitation",
    "UnknownLimitationCodeError",
    "UnknownRecordKindError",
    "UnsupportedVersionError",
    "Verdict",
    "derive_semantic_status",
    "derive_verdict",
    "from_dict",
    "from_json",
    "to_dict",
    "to_json",
    "verify_ref",
]
